name: Go Coverage

on:
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Find Coverage
      run: 'go test -v ./... -covermode=count | grep -E "^coverage: ([0-9\.]*\%) of statements" > coverage.out'

    - name: Set Coverage
      run: echo "CODE_COVERAGE=$(cat coverage.out)" >> $GITHUB_ENV

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Code Coverage

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Code Coverage
          ${{ env.CODE_COVERAGE }}
        edit-mode: replace