name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bufbuild/buf-setup-action@v1


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Download protobuf plugins
      run: "go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest\n 
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28"

    - name: Build
      run: make build

    - name: Test
      run: make test
