name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      

      - name: Download protobuf plugins
        run: "go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest\n 
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28"
      - name: Compile Protos
        run: make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-build-cache: true