name: "protolint"
on:
  pull_request:
  push:
   branches: ['main']

jobs:
  protolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.7.0